#!/bin/bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
CREATE ROLE leiloes_app LOGIN PASSWORD '${DB_APP_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO leiloes_app;
GRANT USAGE ON SCHEMA public TO leiloes_app;
REVOKE CREATE ON SCHEMA public FROM leiloes_app;
CREATE DATABASE leiloes_test OWNER "${POSTGRES_USER}";
SQL
