CREATE ROLE leiloes_owner LOGIN PASSWORD :'senha_owner' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE leiloes_app LOGIN PASSWORD :'senha_app' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
GRANT CONNECT ON DATABASE postgres TO leiloes_owner, leiloes_app;
GRANT USAGE, CREATE ON SCHEMA public TO leiloes_owner;
GRANT USAGE ON SCHEMA public TO leiloes_app;
REVOKE CREATE ON SCHEMA public FROM leiloes_app;
